### ISSUE TITLE
ROS2 subscriber crashes with NotEnoughMemoryException with empty effort array in JointState messages

### ISSUE THREAD

**Issue by jespersmith** [ros2/rmw_fastrtps#191]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 16.04 64 bit
- Installation type:
  - Binary debian packages from deb http://repo.ros2.org/ubuntu/main xenial main
- Version or commit hash:
  - deb http://repo.ros2.org/ubuntu/main xenial main
- DDS implementation:
  - Fast RTPS
- Client library (if applicable):
  - rclpy with command line

#### Steps to reproduce issue

```
ros2 topic pub /eve/joint_states sensor_msgs/JointState "{name: [a,a,a,a,a,a,a], position: [128.0,128.0,128.0,128.0,128.0,128.0,128.0], velocity: [128.0,8.0,128.0,128.0,128.0,128.0,128.0]}"

ros2 topic echo /eve/joint_states sensor_msgs/JointState
```

#### Expected behavior
The ros2 topic echo process doesn't crash

#### Actual behavior
ros2 topic echo crashes with the following message
```
terminate called after throwing an instance of 'eprosima::fastcdr::exception::NotEnoughMemoryException'
  what():  Not enough memory in the buffer stream
Aborted (core dumped)
```
#### Additional information

Only crashes if the number of elements in the JointState.name, JointState.position and JointState.velocity >=7 and the number of elements in JointState.effort = 0. It seems to work if there is at least one element in effort.

**Comment by richiware** [comment]
I was able to reproduce the crash. I've updated Fast-CDR to solve this issue. It was a problem with alignment and zero length arrays at the end of the buffer. Commit eProsima/Fast-CDR@581bc96 contains the solution.

**Comment by akshay-ka** [comment]
Required Info:

Operating System:
    Ubuntu 22.04
Installation type:
    Binaries
ROS2 version:
    Humble
DDS implementation:
    Cyclone DDS
Client library (if applicable):
    rclcpp AND rclpy

Hello,

I get the similar error when I launch the micro-ros node with my robot. However, I'm using `rmw_cyclonedds_cpp`, which is required for my work.
Below is the complete error message.

    [micro_ros_agent-1] terminate called after throwing an instance of  'eprosima::fastcdr::exception::NotEnoughMemoryException'
    [micro_ros_agent-1]   what():  Not enough memory in the buffer stream
    [ERROR] [micro_ros_agent-1]: process has died [pid 4162, exit code -6, cmd '/home/diadem/uros_ws/install/micro_ros_agent/lib/micro_ros_agent/micro_ros_agent serial --dev /dev/esp -b 921600 --ros-args -r __node:=micro_ros_agent'].

@richiware Is there any alternative solution to fix this error ?

**Comment by richiware** [comment]
Unfortunately, we currently don't have the resources to address this. However, please feel free to email support@eProsima.com so we can further find a solution for you.
