### ISSUE TITLE
Switch to use eProsima/RPC over DDS for services?

### ISSUE THREAD

**Issue by calvertdw** [ros2/rmw_fastrtps#204]
Just wondering if there is a need or plan to use the RPC over DDS stuff provided by eProsima for services.

Client code appears to be implemented here: https://github.com/eProsima/RPC/blob/master/src/transports/dds/components/RTPSProxyProcedureEndpoint.cpp

**Comment by richiware** [comment]
First approach was to use it, but it is not interoperable with other rmw implementations. For this reason it's not used.
