### ISSUE TITLE
Usage of ros2/rmw_fastrtps with Fast-RTPS standalone (without ROS2)

### ISSUE THREAD

**Issue by murikill** [ros2/rmw_fastrtps#269]
Hi, 

it is possible to use ros2 publisher with Fast-RTPS standalone programs? I want to proof followed concept: 

I want to start a publisher inside a ros2 system (i.e. demo_node_cpp publisher). On the other side I've compiled Fast-RTPS on my system and I've created an example .idl with usually string variable. Standalone (publisher - subscriber) works Fast-RTPS very well. Next I want to combine these both systems, but currently the topic don't see each other. 

Is it generally possible? And what is the procedere? 

Many thanks!

**Required Info:**

- Operating System:
  - Windows 10
- Installation type:
  - binaries
- Version or commit hash:
  - ros2-crystal-20190314-windows-release-amd64.zip
  - sha256: 7164392cce93b400c6518e7cf80caf466d3ab63a742223eb912c66196b9d86c0
  - md5: 48161fa683e1653bd65e2e48345c37c0
- DDS implementation:
  -  Fast-RTPS 
- Client library (if applicable):
  - rclcpp, rclpy 

#### Steps to reproduce issue
```
build eProsima-RTPS

My .idl: 
struct HelloWorld
{
	string msg;
};

Build an example code with custom .idl as input.
Run HelloWorld.exe subscriber

Install from binaries ROS2 and run talker from demo_node_cpp package.

```

#### Expected behavior

The eProsima subscriber recieves messages from ros2 publisher

#### Actual behavior

It don't happen

**Comment by tfoote** [comment]
Duplicate question asked at: https://answers.ros.org/question/319723/use-ros2-fastrtps-with-standalone-fastrtps-programs/ closing this infavor of that thread.
