### ISSUE TITLE
Compile warning with -Wclass-memaccess

### ISSUE THREAD

**Issue by cottsay** [ros2/rmw_fastrtps#289]
## Bug report

**Required Info:**

- Operating System:
  - Fedora 30
- Installation type:
  - source
- Version or commit hash:
  - 0.7.3
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
Compile from source using system's default compiler, `g++ (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)`

#### Expected behavior
No warnings.

#### Actual behavior
```
src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/src/rmw_response.cpp: In function ‘rmw_ret_t rmw_fastrtps_shared_cpp::__rmw_send_response(const char*, const rmw_service_t*, rmw_request_id_t*, void*)’:
src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/src/rmw_response.cpp:95:45: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct eprosima::fastrtps::rtps::GUID_t’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
   95 |     sizeof(eprosima::fastrtps::rtps::GUID_t));
      |                                             ^
In file included from src/eProsima/Fast-RTPS/include/fastrtps/subscriber/Subscriber.h:23,
                 from src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/src/rmw_response.cpp:19:
src/eProsima/Fast-RTPS/include/fastrtps/rtps/common/Guid.h:342:20: note: ‘struct eprosima::fastrtps::rtps::GUID_t’ declared here
  342 | struct RTPS_DllAPI GUID_t{
      |                    ^~~~~~
```

#### Additional information

`GUID_t` is defined in [fastrtps/include/fastrtps/rtps/common/Guid.h](https://github.com/eProsima/Fast-RTPS/blob/v1.8.0-2/include/fastrtps/rtps/common/Guid.h#L342).
`rmw_request_id_t` is defined in [rmw/include/rmw/types.h](https://github.com/ros2/rmw/blob/0.7.1/rmw/include/rmw/types.h#L172).

There is no conversion that I can see. I was able to suppress the warning with the following change, but I'd like to know if there is another approach that I'm not seeing.
```diff
--- a/rmw_fastrtps_shared_cpp/src/rmw_response.cpp
+++ b/rmw_fastrtps_shared_cpp/src/rmw_response.cpp
@@ -91,8 +91,8 @@ __rmw_send_response(
   assert(info);
 
   eprosima::fastrtps::rtps::WriteParams wparams;
-  memcpy(&wparams.related_sample_identity().writer_guid(), request_header->writer_guid,
-    sizeof(eprosima::fastrtps::rtps::GUID_t));
+  memcpy(static_cast<void *>(&wparams.related_sample_identity().writer_guid()),
+    request_header->writer_guid, sizeof(eprosima::fastrtps::rtps::GUID_t));
   wparams.related_sample_identity().sequence_number().high =
     (int32_t)((request_header->sequence_number & 0xFFFFFFFF00000000) >> 32);
   wparams.related_sample_identity().sequence_number().low =
```

**Comment by clalancette** [comment]
This code has long been refactored into something else, and running the build locally I see no warning anymore.  So I'm going to close this out.
