### ISSUE TITLE
Coverity report data leak

### ISSUE THREAD

**Issue by danielwangksu** [ros2/rmw_fastrtps#304]
It seems ` request.buffer_ = new eprosima::fastcdr::FastBuffer();` did not get deleted

https://github.com/ros2/rmw_fastrtps/blob/62b7534ca154d44db6d7953d6a147d6e6a0abf34/rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp#L70-L102

**Comment by mabelzhang** [comment]
@danielwangksu Thanks for finding these! Do you want to open a PR to address this and #305?

**Comment by clalancette** [comment]
This one has long been refactored and changed to fix the leak, so I'll close this out.
