### ISSUE TITLE
Fix clean up on failure in rmw_* functions

### ISSUE THREAD

**Issue by wjwwood** [ros2/rmw_fastrtps#33]
Currently most `rmw_*` functions do not gracefully clean up on an error, i.e. they can leak memory when the function fails. This pertains mostly to the `rmw_create_*` functions.

Related: https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/pull/32#discussion_r65369237
Connects to #122

**Comment by clalancette** [comment]
Given all of the work that has gone into these functions in the intervening years, I'm going to close this generic issue.  If we find individual functions that don't clean up, we can open separate issues/PRs for those.
