### ISSUE TITLE
Clang Thread Safety Annotation Warning in rmw_get_topic_endpoint_info

### ISSUE THREAD

**Issue by piraka9011** [ros2/rmw_fastrtps#344]
## Bug report

**Required Info:**

- Operating System:
  -  Ubuntu 18.04
- Installation type:
  - Source
- Version or commit hash:
  - [465d15e](https://github.com/ros2/rmw_fastrtps/commit/465d15e2799df638c1e075aec8658381f6a72ff2)
- DDS implementation:
  - FastRTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

Building with `--mixin clang-libcxx`

#### Expected behavior

No warnings

#### Actual behavior

CI results in the [following warnings](https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/lastBuild/warnings23Result/)

```
reading variable 'discovered_names' requires holding mutex 'slave_target->names_mutex_' [-Wthread-safety-analysis]
```

#### Additional information

It looks like there's already a guard [here](https://github.com/ros2/rmw_fastrtps/blob/465d15e2799df638c1e075aec8658381f6a72ff2/rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_participant_info.hpp#L194)
```c++
guid_map_t discovered_names RCPPUTILS_TSA_GUARDED_BY(names_mutex_);
```
but it doesn't look like the macro is captured by TSAN.

**Comment by emersonknapp** [comment]
Just a nitpick - TSAN and Clang Thread Safety Annotations are different things, the title is incorrect
