### ISSUE TITLE
rmw_fastrtps_dynamic_cpp shouldn't require rosidl_typesupport_fastrtps_*

### ISSUE THREAD

**Issue by ivanpauno** [ros2/rmw_fastrtps#382]
#### Feature description

Currently, it's impossible to make a single rmw single typesupport build for `rmw_fastrtps_dynamic_cpp`, as it currently depends on `rosidl_typesupport_fastrtps_c/cpp`:

https://github.com/ros2/rmw_fastrtps/blob/98d14729df0aa6d1ce01d7165d91e7cee257dd5c/rmw_fastrtps_dynamic_cpp/package.xml#L27-L28

That dependency was introduced to use some utility functions available there.
It could be removed if the utility functions are moved to a common package.

**Comment by MiguelCompany** [comment]
> That dependency was introduced to use some utility functions available there.
> It could be removed if the utility functions are moved to a common package

The dependency is there just for the `u16string <-> wstring` conversions. Perhaps `rosidl_runtime_c` and/or `rosidl_runtime_cpp` are good candidates for those functions?

**Comment by ivanpauno** [comment]
Sounds good to me

**Comment by ZhenshengLee** [comment]
Can be closed?

**Comment by MiguelCompany** [comment]
I don't think so, since `rmw_fastrtps_dynamic_cpp` still requires `rosidl_typesupport_fastrtps_*` [here](https://github.com/ros2/rmw_fastrtps/blob/rolling/rmw_fastrtps_dynamic_cpp/CMakeLists.txt#L47-L48)
