### ISSUE TITLE
[rmw_fastrtps_dynamic_cpp] Typesupport implementation leaks and it relies in conceptually broken cpp

### ISSUE THREAD

**Issue by ivanpauno** [ros2/rmw_fastrtps#428]
See discussion in:
- https://github.com/ros2/rmw_cyclonedds/issues/219
- https://github.com/ros2/rmw_cyclonedds/pull/228

#228 can directly be applied here.

**Comment by ivanpauno** [comment]
@iuhilnehc-ynos @richiprosima FYI

**Comment by MiguelCompany** [comment]
@ivanpauno @iuhilnehc-ynos I am currently addressing this on [this branch](https://github.com/eProsima/rmw_fastrtps/tree/bugfix/428)

I still want to do more testing before opening a PR for it. Will do that on Monday

**Comment by MiguelCompany** [comment]
@ivanpauno PR #429 is ready for review. All `reinterpret_cast<std::vector<unsigned char> *>` have been removed, so I think it also fixes #219
