### ISSUE TITLE
ROS2 CLI tests failing when run against rmw_fastrtps_cpp

### ISSUE THREAD

**Issue by hidmic** [ros2/rmw_fastrtps#531]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu Focal 20.04 amd64
- Installation type:
  - From source
- Version or commit hash:
  - Current [`master`](6c4f17af4c65463406dac0843b5957cd9aff7e01)
- DDS implementation:
  - Fast-DDS
- Client library (if applicable):
  - `rclpy`

#### Steps to reproduce issue
I have not been able to reproduce this issue locally, but it has been happening since late last week 
(https://ci.ros2.org/view/nightly/job/nightly_linux_repeated/2279).

#### Expected behavior
CLI tests pass.

#### Actual behavior

CLI tests fail with something like:

```
[RTPS_TRANSPORT_SHM Error] Failed to create segment 56b71f66bffcdbb2: boost::interprocess_exception::library_error -< Function compute_per_allocation_extra_size
[RTPS_MSG_OUT Error] boost::interprocess_exception::library_error -< Function init
```

#### Additional information

Logs are coming from [within Fast-DDS](https://github.com/eProsima/Fast-DDS/blob/e0ba220d878b5f3ba858256bb72332128cd68033/src/cpp/utils/shared_memory/SharedMemSegment.hpp#L153-L195).

**Comment by hidmic** [comment]
@EduPonz @MiguelCompany I'd really value for input here. The problem isn't obvious to me.

**Comment by MiguelCompany** [comment]
@hidmic I've been analyzing this.

**What is happening?**
As the CI is killing some participants in an uncontrolled way, the shared memory space is most probably being exhausted. Fast DDS shows the error but keeps working, though communication will only be through UDP in that case.

The errors are logged in case the user has configured the participant to only use the SHM transport. If that is the case and there is no SHM space available, the participant creation [will fail](https://github.com/eProsima/Fast-DDS/blob/8def3913d848b181fe0b499a1ebeb6efd897cb86/src/cpp/rtps/RTPSDomain.cpp#L184). 

**What can be done?**
We suggest running `fastdds shm clean` before each test execution, which will remove any unused shared memory files. I don't know if that is possible for every test but for the CLI ones it could be done from [test_cli.py](https://github.com/ros2/ros2cli/blob/master/ros2action/test/test_cli.py).

I haven't studied the test thoroughly, but if it only checks the contents of stdout, another option would be to make Fast DDS output the logs to stderr. That can be achieved with the following XML configuration:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<dds>
    <log>
        <!--
        Clear consumers
        -->
        <use_default>FALSE</use_default>

        <!--
        StdoutErrConsumer will output Warning and Error messages to stderr by default
        -->
        <consumer>
            <class>StdoutErrConsumer</class>
        </consumer>
    </log>
</dds>
```

As a last resource, we could change the code on Fast DDS to move the level of those messages from error to warning (as the latter is not reported by default), but we'd prefer to leave them as they are.

**Comment by MiguelCompany** [comment]
> Can you confirm that [`destroy_participant()`](https://github.com/ros2/rmw_fastrtps/blob/7cb3bd0f73f332f9c27caf505b5bcd1b055c0ec7/rmw_fastrtps_shared_cpp/src/participant.cpp#L324-L392) does in fact take out the participant?

Yes, it [this lines](https://github.com/ros2/rmw_fastrtps/blob/7cb3bd0f73f332f9c27caf505b5bcd1b055c0ec7/rmw_fastrtps_shared_cpp/src/participant.cpp#L379-L381) don't show an error, the participant resources should have been correctly cleaned up.

To check for an undead participant, you could `ls /dev/shm/fastrtps*`. I have seen that sometimes, the ros 2 daemon stays alive for a while and is suddenly killed (with a SIGKILL), resulting in destroy_participant not being called at all.

A similar problem arises with test timeouts, where ctest may also SIGKILL the process.

**Comment by clalancette** [comment]
We haven't seen this in quite a while, so I'm going to close this out.  We'll open a new issue if we come across it again.
