### ISSUE TITLE
could not create publisher/subscription: Type support not from this implementation

### ISSUE THREAD

**Issue by TSC21** [ros2/rmw_fastrtps#541]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- Version or commit hash:
  - rmw-fastrtps `5.0.0-2focal.20210519.024652`
- DDS implementation:
  - FastDDS 2.3.1 in ROS2 Galactic
- Client library (if applicable):
  - rclcpp in ROS2 Galactic

#### Steps to reproduce issue
The ROS2 packages are being cross-compiled using https://github.com/ros-tooling/cross_compile, which supposedly configures the build environment correctly. They are then deployed to an `arm64` platform and run there.

I am not able to start any node when setting `RMW_IMPLEMENTATION=rmw_fastrtps_cpp` in ROS2 Galactic, throwing the error bellow. The same doesn't happen with ROS2 Foxy.

#### Expected behavior
Being able to start the nodes and use the ROS2 CLI to echo topics, etc.

#### Actual behavior
The bellow shows when starting a ROS2 node with a publisher:

```sh
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
what():  could not create publisher: Type support not from this implementation. Got:
    error not set
    error not set
while fetching it, at /tmp/binarydeb/ros-galactic-rmw-fastrtps-cpp-5.0.0/src/publisher.cpp:115, at /tmp/binarydeb/ros-galactic-rcl
-3.1.2/src/rcl/publisher.c:114
```

#### Additional information

If the type support is not from "this" implementation, what should it be then? Does it mean that one has to build the packages with the rmw_implementation set in the CMakeLists.txt file of the package, targeting then RMW we are going to use the package on? (for example, if I build in Galactic, the default rmw_implementation will be `rmw_cyclonedds_cpp`). Or is that not relevant here? (shouldn't be IMO)

@MiguelCompany

**Comment by TSC21** [comment]
Any feedback that can be provided here?

**Comment by 1r0b1n0** [comment]
Hi, I had the same problem on one of my projets.
To use a ROS2 workspace with fastDDS, its library must be present during compilation.  Having installed fastDDS during runtime is not enough.
My solution was to simply recompile the workspace after installing "ros-galactic-rmw-fastrtps-cpp".

**Comment by clalancette** [comment]
@MiguelCompany any thoughts on what might be happening here?

**Comment by MiguelCompany** [comment]
@clalancette I think the scenario may be as follows:

* A user installs galactic-core from packages
* The user creates a package with message definitions and builds
  * As only rmw_cyclonedds_cpp is installed, and it only requires the introspection type support, only that type support is generated
* The user then installs the rmw_fastrtps_cpp package, and sets `RMW_IMPLEMENTATION=rmw_fastrtps_cpp`
* When the publisher is created, the introspection type support is passed in, giving the error

Something that can be tried, apart from @1r0b1n0 suggestion of rebuilding the workspace, is to use `RMW_IMPLEMENTATION=rmw_fastrtps_dynamic_cpp`, which expects the introspection type support to be passed in.

@TSC21 Could you try that approach?

**Comment by huichengongzi** [comment]
Hi, I had the some problem in my project. reprodection as that:
1, apt-get install ros-galactic-rmw-fastrtps-cpp
2, export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
3, ros run ...
Solution is that clean my project and rebuild it, then ros run, it can work fine.

**Comment by zjeffer** [comment]
Deleting the build & install folders and then rebuilding the package with `ros-galactic-rmw-fastrtps-cpp` installed fixed the issue, thank you @huichengongzi @1r0b1n0

**Comment by ZhenshengLee** [comment]
this issue happens in ros2 source build too.

```sh
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
```

then rebuild ros2 solves this issue.

**Comment by clalancette** [comment]
Sounds good, thanks!
