### ISSUE TITLE
No dependency information found for libfastrtps.so.2

### ISSUE THREAD

**Issue by xander-m2k** [ros2/rmw_fastrtps#569]
## Bug report

**Required Info:**

- Operating System:
  - Debian Buster
- Installation type:
  - Trying to compile ROS packages into binaries which are using FastRTPS as dependency
- DDS implementation:
  - Fast-RTPS

#### Steps to reproduce issue
It's pretty hard to reproduce, and that's maybe why no one finds this. 
You have to binary build ROS2 Foxy from source. Generate binary conf with `bloom-generate rosdebian` and build the package with `dpkg-buildpackage -b -rfakeroot -us -uc`, after that install each package (`.deb`) after building.
The order to build the packages:
<details>
  <summary>To list the order, click here...</summary>
    ament_package
ament_lint
ament_cmake_core
ament_flake8
gtest_vendor
ament_pep257
ament_cmake_libraries
ament_cmake_export_libraries
ament_cmake_python
ament_cmake_export_dependencies
ament_cmake_test
ament_cmake_include_directories
ament_cmake_export_targets
ament_cmake_export_definitions
ament_cmake_export_include_directories
ament_cmake_export_link_flags
ament_cmake_version
ament_cmake_export_interfaces
ament_cmake_target_dependencies
ament_copyright
ament_cmake
ament_cmake_gtest
ament_cmake_pytest
gmock_vendor
ament_cmake_gmock
domain_coordinator
ament_index_python
fastcdr
ament_lint_cmake
ament_xmllint
ament_cmake_lint_cmake
rpyutils
ament_cmake_copyright
uncrustify_vendor
ament_cppcheck
ament_cpplint
ament_cmake_cppcheck
ament_uncrustify
ament_cmake_cpplint
ament_cmake_uncrustify
ament_cmake_xmllint
ament_cmake_flake8
foonathan_memory_vendor
ament_cmake_pep257
ament_lint_common
ament_lint_auto
ament_cmake_ros
rosidl_adapter
rosidl_typesupport_interface
rosidl_parser
connext_cmake_module
rosidl_cmake
rosidl_generator_dds_idl
fastrtps
fastrtps_cmake_module
python_cmake_module
cyclonedds
rmw_implementation_cmake
spdlog_vendor
tracetools
osrf_pycommon
launch
ament_index_cpp
launch_testing
osrf_testing_tools_cpp
launch_testing_ament_cmake
python_qt_binding
tango_icons_vendor
qt_gui
google_benchmark_vendor
tinyxml2_vendor
eigen3_cmake_module
ament_cmake_google_benchmark
performance_test_fixture
rosidl_runtime_cpp
console_bridge_vendor
yaml_cpp_vendor
orocos_kdl
urdfdom_headers
tinyxml_vendor
shared_queues_vendor
urdfdom
ament_mypy
libcurl_vendor
mimick_vendor
rcutils
rosidl_runtime_c
rcpputils
rmw
rosidl_typesupport_connext_cpp
libyaml_vendor
rosidl_typesupport_fastrtps_cpp
rcl_logging_log4cxx
rosidl_typesupport_fastrtps_c
rcl_logging_noop
rcl_logging_spdlog
rcl_yaml_param_parser
class_loader
urdf
ament_cmake_auto
rviz_assimp_vendor
pluginlib
rviz_ogre_vendor
qt_gui_py_common
resource_retriever
zstd_vendor
test_interface_files
rosidl_generator_c
rosidl_typesupport_connext_c
rosidl_typesupport_c
rosidl_typesupport_cpp
rmw_connext_cpp
rosidl_generator_cpp
rosidl_generator_py
rosidl_default_runtime
rosidl_default_generators
builtin_interfaces
rmw_dds_common
rmw_fastrtps_shared_cpp
rmw_cyclonedds_cpp
rcl_interfaces
rosgraph_msgs
</details>

If the `fastrtps_cmake_module` package here does not trigger the error, please continue the list until you do find it triggered, I found it to trigger mostly on msgs packages. Right now I am bypassing this error with the [following solution](https://stackoverflow.com/questions/11238134/dpkg-shlibdeps-error-no-dependency-information-found-for).

#### Expected behavior
Compile without error
#### Actual behavior
`ERROR: no dependency information found for /opt/ros/foxy/fastrtps/lib/libfastrtps.so.2`

**Comment by clalancette** [comment]
Given that both Buster and Foxy are now EOL, I'm going to close this out.  If you are still having problems, please feel free to open a new issue.
