### ISSUE TITLE
It is possible to know what ROS2 topic publish the message ?

### ISSUE THREAD

**Issue by FranciscoSantiago15** [ros2/rmw_fastrtps#585]
Hello,

I'm working in a project using ROS2 and i would like to know if it is possible to know the topic o publish the message.
For example, imagine that i have 3 subscribers (Sub1, Sub2and Sub3) and the callback function is just printing the data of the message, if i publish a message to Sub3 can i know in the callback function what topic as used ?

```
self.test_sub1 = self.create_subscription(Bool, "Sub1", self.callback, 10)
self.test_sub2 = self.create_subscription(Bool, "Sub2", self.callback, 10)
self.test_sub3 = self.create_subscription(Bool, "Sub3", self.callback, 10)

def callback(self, msg):
        print(msg.data)
        print(topic_name)       -> can i know this ?
```

**Comment by clalancette** [comment]
For questions like this, please use https://answers.ros.org.  That's our central site for questions and answers.  I'll close this out for now.
