### ISSUE TITLE
Found incoherent method calls in rmw_create_subscription.

### ISSUE THREAD

**Issue by Oscarchoi** [ros2/rmw_fastrtps#647]
## Bug report

In the following snippet of code, `associate_reader(…)`(line:104) and `dissociate_writer(…)`(line:114) do not correspond to each other.
https://github.com/ros2/rmw_fastrtps/blob/ccea7a356900a16a2872670b67952c99a72ab65d/rmw_fastrtps_cpp/src/rmw_subscription.cpp#L101-L124
Considering that `rmw_ds_common::GraphCache` separates the gid storage of readers and writers, I think it has to dissociate the reader that was associated right above. In `rmw_create_publisher(...)`, the corresponding counterpart of the codes, the associated writer is dissociated when publishing fails.

I think it should be modified as follows. https://github.com/Oscarchoi/rmw_fastrtps/commit/e997378b7fd8edbee352815aebe6bfb06e029498 If the existing code is not intended, is it okay to PR the above changes?  
By the way, the test code assumes that `rmw_create_subscription` will always succeed, so this fallback code has no effect.

**Comment by fujitatomoya** [comment]
> I think it should be modified as follows. https://github.com/Oscarchoi/rmw_fastrtps/commit/e997378b7fd8edbee352815aebe6bfb06e029498 If the existing code is not intended, is it okay to PR the above changes?

@MiguelCompany i think this is a bug, can you confirm?

**Comment by Oscarchoi** [comment]
I fixed formattings: https://github.com/Oscarchoi/rmw_fastrtps/commit/763103944b2e02ea70a66ecf21b509f6cb75e7c8

**Comment by MiguelCompany** [comment]
@fujitatomoya I think @Oscarchoi is right, and the proposed changes seem correct.

**Comment by fujitatomoya** [comment]
@Oscarchoi as @MiguelCompany mentioned, this needs to be fixed as bug. Could you create PR with using your fix? I am happy to review 👍

**Comment by Oscarchoi** [comment]
Thank you both for confirmation! 😃
I'll create PR soon and notify you.

**Comment by clalancette** [comment]
This was fixed by #649 , so closing this out.
