### ISSUE TITLE
foxglove-bridge err occur when use fastrtps

### ISSUE THREAD

**Issue by sgf201** [ros2/rmw_fastrtps#678]
## Bug report

**Required Info:**

- Operating System:
  docker ros::humble
- Installation type:
  docker
- Version or commit hash:
 
- DDS implementation:
 fastdds
- Client library (if applicable):
 

#### Steps to reproduce issue
sudo apt install ros-humble-foxglvoe_bridge*
ros2 launch foxglove_bridge foxglove_bridge_launch.xml

#### Expected behavior
no error msg

#### Actual behavior
![img_v2_3dd81455-bce1-4aaa-a7b3-4c8b7b134eag](https://user-images.githubusercontent.com/5253415/227090056-3bc4a695-35a1-40eb-a466-347f2f87654c.jpg)

#### Additional information
no error occur  when I change dds to cyclonedds

#### Implementation considerations
no error occur  when I change dds to cyclonedds

![R5pzKlt1aD](https://user-images.githubusercontent.com/5253415/227090221-93f68f82-d3fc-4c32-a4cf-36bec494db72.jpg)

![ucnOOnpd5b](https://user-images.githubusercontent.com/5253415/227090244-1b828d5b-8429-4582-82f7-9269f9216601.jpg)

**Comment by sgf201** [comment]
seems like get_default_topic_qos  the qos_policies is a abnormal value

**Comment by clalancette** [comment]
@amacneil Could you have somebody take a quick look at this and see if this is something on the foxglove side or the Fast-RTPS side?

**Comment by sgf201** [comment]
https://github.com/foxglove/ros-foxglove-bridge/pull/205

**Comment by sgf201** [comment]
done
