### ISSUE TITLE
ROS2 lifecycle nodes fail to communicate

### ISSUE THREAD

**Issue by Jayden-F** [ros2/rmw_fastrtps#691]
## Bug report

**Required Info:**

- Operating System:
  - 
- Installation type: Ubuntu 22.04
  - 
- Version or commit hash: ros-humble-rmw-fastrtps-cpp/jammy, now 2.6.4-1jammy.20230425.234452
  - 
- DDS implementation:
  - 
  - FAST RTPS
- Client library (if applicable):
  - 
  - rclcpp

#### Steps to reproduce issue
<!-- Detailed instructions on how to reliably reproduce this issue http://sscce.org/
``` code that can be copy-pasted is preferred ``` 

https://github.com/ros-planning/navigation2/issues/3560

#### Expected behavior
Nodes are started by lifecycle manager

#### Actual behavior
Node and lifecycle manager are waiting for each other.

**Comment by clalancette** [comment]
Given that there is no information in here, I'm going to close this out.  If you have a question, please open it on https://answers.ros.org and we can followup there.

**Comment by Jayden-F** [comment]
My markdown as malformed. Here is the updated problem
