### ISSUE TITLE
200% cpu usage in aarch64 using fastdds

### ISSUE THREAD

**Issue by sgf201** [ros2/rmw_fastrtps#709]
## Bug report
high cpu usage when no node is running (200%)
ros2 launch  then ctrl c, but this process takes 200% forever
**Required Info:**

- Operating System:
  ubuntu20
- Installation type:
  binary
- Version or commit hash:
  ros2 Humble
- DDS implementation:
  Fast-RTPS
- Client library (if applicable):
  rclcpp

#### Steps to reproduce issue

ros2 launch then htop
![image](https://github.com/ros2/rmw_fastrtps/assets/5253415/faffeca7-5fa2-442b-b7be-7d3e87fd5dd8)

**Comment by fujitatomoya** [comment]
> ubuntu20

Humble officially supports Ubunutu 22.04, https://docs.ros.org/en/humble/Releases/Release-Humble-Hawksbill.html#supported-platforms

with the following test using humble latest release, i cannot reproduce the issue.

```bash
> root@tomoyafujita:~# ros2 run demo_nodes_cpp talker_loaned_message
> root@tomoyafujita:~# ros2 run demo_nodes_cpp listener
```

and then,

```bash
root@tomoyafujita:~# ros2 node list -a
/_ros2cli_daemon_0_58db6f21dba9462b9297f13367ed8a16
root@tomoyafujita:~# top
```

**Comment by fujitatomoya** [comment]
i think `daemon` can be expensive for discovery process if we have large ROS 2 network with many endpoints. but this is exactly why and where daemon comes to play. daemon absorbs discovery cost for `ros2cli`. after given time for the discovery, it should be not so expensice.
