### ISSUE TITLE
Magic_numbers in calculateMaxSerializedSize

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/rmw_fastrtps#72]
This is a follow-up of https://github.com/ros2/rmw_fastrtps/issues/36
There are still magic numbers ([101](https://github.com/ros2/rmw_fastrtps/blob/8623ccde0fbdeab8142ed4062978c977446327f0/rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp#L772), [257](https://github.com/ros2/rmw_fastrtps/blob/8623ccde0fbdeab8142ed4062978c977446327f0/rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp#L805) and [100](https://github.com/ros2/rmw_fastrtps/blob/8623ccde0fbdeab8142ed4062978c977446327f0/rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp#L426)) use to determine the maximum size of a sample.
It would be good to investigate if we can get rid of them and improve the logic of the [MaxSize calculation](https://github.com/ros2/rmw_fastrtps/blob/8623ccde0fbdeab8142ed4062978c977446327f0/rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp#L135)

**Comment by allenh1** [comment]
@mikaelarguedas This might also be something I could work on

**Comment by mikaelarguedas** [comment]
@allenh1 Is this one still on your radar ?

**Comment by allenh1** [comment]
Yep -- I was waiting on the refactor to finish, but looks like I can go after it now.

**Comment by mikaelarguedas** [comment]
There is now only [one magic number left](https://github.com/ros2/rmw_fastrtps/blob/79d8dc4ed25306ce44d97fede4d8fa0f474f7a34/rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp#L427).

@richiprosima I see there is a [todo in your name](https://github.com/ros2/rmw_fastrtps/blob/79d8dc4ed25306ce44d97fede4d8fa0f474f7a34/rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp#L443) to modify it, do you have any insight as of if this variable should be kept ?

**Comment by richiprosima** [comment]
That value is inherited from when there was only preallocated memory policy in FastRTPS, and dynamic types had to have a maximum length. For sequences/arrays the maximum length was 100. Now ROS2 uses preallocated_with_realloc memory policy and maximum lengths are not needed.

**Comment by dirk-thomas** [comment]
@richiprosima can you please propose a patch how to get rid of this variable. It isn't clear to us how to remove it cleanly.

**Comment by richiware** [comment]
I'm working on it

**Comment by richiware** [comment]
PR #152 removes those magic numbers.

**Comment by mikaelarguedas** [comment]
All magic numbers have now been removed :tada: closing
