### ISSUE TITLE
ignore_local_publications is not supported

### ISSUE THREAD

**Issue by dhood** [ros2/rmw_fastrtps#76]
In `rmw_create_subscription`, the `ignore_local_publications` flag is [not currently used](https://github.com/ros2/rmw_fastrtps/blob/075bc487bee6c9a6fb6edf8f963177924040613c/rmw_fastrtps_cpp/src/functions.cpp#L1013) for `rmw_fastrtps_cpp` ([as is done in `rmw_connext_cpp`](https://github.com/ros2/rmw_connext/blob/58e724ba256263680f53df6ca338f412e0068fd1/rosidl_typesupport_connext_cpp/resource/msg__type_support.cpp.em#L285-L298))

**Comment by MaximeAubanel** [comment]
It seems that it is still not supported. Can we have an update on this ?

**Comment by ste93** [comment]
Hi all, are there any updates on this topic?

**Comment by hidmic** [comment]
@ste93 see #536

**Comment by ste93** [comment]
@hidmic thanks!

**Comment by EduPonz** [comment]
I think this can be closed
