### ISSUE TITLE
FindFastRTPS.cmake uses the env var FASTRPCHOME instead of FASTRTPSHOME

### ISSUE THREAD

**Issue by jespersmith** [ros2/rmw_fastrtps#90]
In FindFastRTPS.cmake:

if($ENV{FASTRPCHOME})
    set(FastRTPS_HOME $ENV{FASTRPCHOME})
endif()

This should of course be

if($ENV{FASTRTPSHOME})
    set(FastRTPS_HOME $ENV{FASTRTPSHOME})
endif()

**Comment by dirk-thomas** [comment]
@jespersmith Can you please create a PR with the suggested patch.

@richiprosima Can you please comment on it since you wrote this originally.

**Comment by jespersmith** [comment]
@dirk-thomas No. I'm using this file in another project, just pointing out the error in the documentation.

**Comment by dirk-thomas** [comment]
@jespersmith You can edit the file through the GitHub web interface and it will automatically create a fork for you, add a commit with your change and create a pull request for it. We can then trigger a CI build for the PR to ensure it continues working (which I would expect).

**Comment by jespersmith** [comment]
@dirk-thomas That's easy. See pull request #91

**Comment by dirk-thomas** [comment]
@jespersmith Thank you!
